---
title: "donor_bias"
author: "Sean Maden"
date: "2022-12-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

libv <- c("lute", "ggplot2", "GGally")
sapply(libv, library, character.only = T)
```

# Randomize donor data

We  start by generating the randomized marker data for `r ndonor` donors.

```{r}
# get simulated marker data
ndonor = 5
dt <- lute::rand_donor_marker_table(ndonor, gindexv = c(1,1,2,2,3,3), ktotal = 3)
dt
```

Next, we generate the combined marker signals from the provided donors.

```{r}
# get mean of signals from all donors
dt$donor.combn.all.mean <- apply(dt[,grepl("donor", colnames(dt))], 1, mean)
dt$donor.combn.all.median <- apply(dt[,grepl("donor", colnames(dt))], 1, median)
# get list of combination indices
# lc <- lapply(seq(2,(ndonor-1)), function(ii)combn(ndonor, ii))
```

# Plots -- marker signals

PCA by donor

```{r}
df.pca <- t(dt[,grepl("donor", colnames(dt))])
rpca <- prcomp(df.pca)
# assign pca labels with perc. sd
percv <- round(100*rpca$sdev/sum(rpca$sdev),0)
colnames(rpca$x) <- paste0(colnames(rpca$x), " (",percv,"%)")
# make scatterplot
num.markers <- length(unique(dt$marker))
num.types <- length(unique(dt$type))
dfp <- as.data.frame(rpca$x)
dfp$x <- dfp[,1]; dfp$y <- dfp[,2]
dfp$donor <- rownames(df.pca)
dfp$donor.summary <- ifelse(grepl("mean|median", dfp$donor), TRUE, FALSE)
ggplot(dfp, aes(x = x, y = y, color = donor, shape = donor.summary)) + 
  geom_point(size = 4, alpha = 0.5) + xlab(colnames(dfp)[1]) +
  ylab(colnames(dfp)[2]) + 
  ggtitle(paste0("PCA across markers; ",
                 "Num. markers = ", num.markers, 
                 "; Num. types = ", num.types))
```

PCA by donor;type

```{r}
ntype <- length(unique(dt$type))
cndv <- colnames(dt)[grepl("^donor.*", colnames(dt))]
ndonorcat <- length(cndv)
catv <- paste0(rep(cndv, each = ntype), ";", 
               rep(paste0("type", seq(ntype)), times = ndonorcat))
df.pca <- do.call(rbind, lapply(catv, function(cati){
  colfilt <- grepl(gsub(";.*", "", cati), colnames(dt))
  rowfilt <- grepl(gsub(".*;", "", cati), dt$type)
  dtf <- dt[rowfilt, colfilt]
}))
rownames(df.pca) <- catv
rpca <- prcomp(df.pca)
# assign pca labels with perc. sd
percv <- round(100*rpca$sdev/sum(rpca$sdev),0)
colnames(rpca$x) <- paste0(colnames(rpca$x), " (",percv,"%)")
# make scatterplot
dfp <- as.data.frame(rpca$x)
dfp$x <- dfp[,1]; dfp$y <- dfp[,2]
dfp$donor <- gsub(";.*", "", rownames(df.pca))
dfp$type <- gsub(".*;", "", rownames(df.pca))
ggplot(dfp, aes(x = x, y = y, color = donor, shape = type)) + 
  geom_point(size = 4, alpha = 0.5) + 
  ggtitle(paste0("PCA by donor, marker; Num. markers = ", ncol(df.pca))) +
  xlab(colnames(dfp)[1]) + ylab(colnames(dfp)[2])
```

```{r}
ggpairs(dfp, top = list(continuous="na"), columns = seq(ncol(df.pca)), 
        map = ggplot2::aes(color=donor, shape=type), 
        title = paste0("Num. markers = ", ncol(df.pca)))
```

```{r}
dfp <- data.frame(pc = colnames(rpca$x), sd = rpca$sdev)
ggplot(dfp, aes(x = pc, y = sd)) + geom_bar(stat="identity") + theme_bw() +
  ggtitle(paste0("Num. markers = ", ncol(df.pca))) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
Predictions by donor

```{r}
# get decon args
# prop.val <- 0.1
# lpv <- list(c(prop.val, 1-prop.val))
# lsv <- list(c(1, 10))
lpv <- make_lpv()
num.sim <- length(lpv)
size1 <- 1
size2 <- 100
lsv <- lapply(seq(num.sim), function(ii){c(size1, size2)})

# get params
ndonor <- length(colnames(dt)[grepl("donor", colnames(dt))])
ntype <- length(unique(dt$marker))
# run decon
ld <- lapply(cndv, function(donori){
  cnvf <- c(donori, "type"); dtf <- dt[,cnvf]
  lgvi <- lapply(seq(ntype), function(jj){
    dtf[dtf[,2]==paste0("type", jj),1]
  })
  # rep up to num sim
  lgv.in <- lapply(seq(num.sim), function(ii){lgvi})
  decon_analysis(lgv = lgv.in, lpv = lpv, lsv = lsv)
})
names(ld) <- cndv
```

# Plots -- predictions

```{r}
# get plot data
ztrans <- FALSE
dfp <- do.call(rbind, lapply(ld, function(li){
  dfresi <- li$dfres
  dfresi <- dfresi[dfresi$zs_transform==ztrans,c(1,2)]
  }
))
# dfp$donor <- rownames(dfp)
# make grid of scatterplots, corr
pairs(dfp[,grepl("bias.*", colnames(dfp))])
```
