---
title: "The lute user's guide"
author:
- Sean K. Maden
date: "`r format(Sys.time(), '%d %B, %Y')`"
bibliography: bibliography.bib
package: lute
output:
  BiocStyle::html_document:
    code_folding: show
    toc: no
    tocfloat: no
  BiocStyle::pdf_document: 
    toc: no
    toc_depth: 0
vignette: > 
  %\VignetteIndexEntry{The lute user's guide}
  %\VignetteDepends{RCurl}
  %\usepackage[UTF-8]{inputenc} 
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# How to use this guide

This User's Guide describes how to use `lute`, a framework for bulk 
transcriptomics deconvolution. An introduction to deconvolution experiments is 
provided, followed by a description of the framework and a small experiment 
using example data.

# Deconvolution overview

## Definition

Deconvolution is the process of quantifying signal from a signal mixture, which
is sometimes called a signal convolution. In a deconvolution experiment we 
typically try to predict signal amounts as accurately as possible. In the case 
of bulk transcriptomics deconvolution, the signals are cell types and the signal 
mixture is a cell mixture, such as a bulk tissue specimen containing multiple 
cell types.

## Experiment ingredients

To perform deconvolution, we need a few ingredients: a deconvolution algorithm, 
and key inputs for the algorithm. Most deconvolution algorithms attempt to solve
the following for $P$ as quickly and accurately as possible:

$$p \leftarrow [Y, Z]$$
Where we have the following terms:

* $P$ : K-length vector of cell type proportions.

* $Z$ : Signature matrix of dimensions G signature genes by K cell types.

* $Y$ : The convoluted signals matrix of dimensions G signature genes by J bulk samples.

While we can pass the above variables to a reference-based deconvolution algorithm,
we should also think about whether certain types of data transformations, such as
the scale of signals in $Z$, and preprocessing steps, such as the selection 
criteria for the $G$ marker genes, can ultimately lead us to improved outcomes.

## Pseudobulking

It's important to note that many experiments conduct a type of simulation called
pseudobulking, which is to derive an artificial bulk sample as a mixture of 
type-specific signals. This looks like the following:

$$Y = Z * P$$

While this is perhaps the simplest representation of the pseudobulk equation, it
is important to note the importance of a cell size scaling factor $S$ for 
improving deconvolution outcomes. $S$ is a vector of $K$ length which reflects 
the relative sizes of each cell type, and it can be applied either to $Z$ prior
to deconvolution, or applied when generating the pseudobulk sample as follows:

$$Y = Z * P * S$$

## Strict deconvolution versus deconvolution preparation

To aid an understanding of how a deconvolution method works, it is important to
have clear terminology. Throughout `lute` documentation, we refer to ``strict deconvolution.'' By this, we mean any method for calculating $p$ given some $Y$ 
and $Z$. Some examples include Non-negative Least Squares (NNLS) and Ordinary 
Least Squares (OLS), and ridge regression.

By contrast to strict deconvolution, deconvolution preparation can be any step 
conducted prior to strict deconvolution, and in particular steps to prepare $Y$ 
and $Z$, such as to mitigate cross-assay biases, reduce marker dimensions, weight markers according to relative importance, remove confounding variation, and more.

